In [ ]:
!pip  install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 5.1 MB/s
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.5 which is incompatible.
Successfully installed pandas-1.3.5

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks'
!ls

/content/drive/My Drive/Colab Notebooks
'Fundamentos de ML - Platzi'
'Informe TPO G7 - Domotica OpenCV.gdoc'
'Intro to AI - Platzi'
'Math for Data science - Platzi'
'Pandas - Platzi'
 Python-con-aplicaciones-a-las-matematicas-ingenieria-y-finanzas-pdf.pdf
'Reinforcement Learning - Simonini'
 Udacity

In [ ]:
'Hola {}'.format('bla bla bla bla')

'Hola bla bla bla bla'

In [ ]:
!mkdir /content/drive/My\ Drive/Colab\ Notebooks/db

In [ ]:
dir_pandas = '/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/{}'.format('test.xls')
dir_pandas

'/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/test.xls'

In [ ]:
import pandas as pd
pd.__version__
import numpy as np

In [ ]:
dict_data = {
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}
dict_data

{'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9.0],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'edad': [10, 9, 13, 14, 12, 11, 12],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch']}

In [ ]:
df = pd.DataFrame(dict_data)
df

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

In [ ]:
dir_pandas = '/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/{}'.format('test.csv')
dir_pandas

'/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/test.csv'

In [ ]:
df.to_csv(dir_pandas, index = False)

In [ ]:
!ls /content/drive/My\ Drive/Colab\ Notebooks/Pandas\ -\ Platzi/db

test.csv

In [ ]:
df_read = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/test.csv')
df_read

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

In [ ]:
df.to_csv(dir_pandas, sep = '|', index = False)

In [ ]:
dir_pandas = '/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/{}'
dir_pandas

'/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/{}'

In [ ]:
df.to_excel(dir_pandas.format('test.xlsx'), index=False, sheet_name='Hoja_uno')

In [ ]:
dir_pandas.format('test.xlsx')

'/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db/test.xlsx'

In [ ]:
pd.read_excel(dir_pandas.format('test.xlsx'))

ImportError: ignored

In [ ]:
df.to_json(dir_pandas.format('test.json'))

In [ ]:
pd.read_json(dir_pandas.format('test.json'))

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

Pickel: archivo binario de data comprimida, usada en db de tamaño medio

In [ ]:
df.to_pickle(dir_pandas.format('test.pkl'))

In [ ]:
pd.read_pickle(dir_pandas.format('test.pkl'))

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

Parquet: formato de Apache para big data

In [ ]:
df.to_parquet(dir_pandas.format('test.parquet'))

In [ ]:
df.to_hdf(dir_pandas.format('test.hdf'),key='data',format='table')

ImportError: ignored

In [ ]:
pd.read_parquet(dir_pandas.format('test.parquet'))

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

HDF: formato usado en big data muy utilizado en Hadoop

In [ ]:
pd.read_hdf(dir_pandas.format('test.hdf'))

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0